M48
; DRILL file {KiCad (6.0.8)} date Wed Nov 16 21:33:02 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-16T21:33:02-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1300
%
G90
G05
T1
X4.3504Y-2.0177
X4.3504Y-3.9961
X7.8642Y-2.0177
X7.89Y-4.0354
T0
M30
